# Generated by Django 3.2.3 on 2021-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_remove_trainer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
