# Generated by Django 3.2.3 on 2021-09-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_alter_trainer_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.BigIntegerField(null=True),
        ),
    ]
